<?php
/**
 *
 * DO NOT EDIT THIS FILE!
 *
 * Place your custom settings in a file config_override.php to make sure those settings do not get lost with an update.
 *
 *
 * CONSTANTS you can override:
 *
 * COM_EVENTGALLERY_IMAGE_FOLDER_PATH - the path to the image directory. Make sure it has a trailing slash.
 * COM_EVENTGALLERY_IMAGE_FOLDER_PATH_WEB - the url path to the image directory. You need to have a valid value in here
 *                                          if you want to share images using Facebook or make them available for download
 *
 *
 * @package     Sven.Bluege
 * @subpackage  com_eventgallery
 *
 * @copyright   Copyright (C) 2005 - 2013 Sven Bluege All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */


// no direct access
defined('_JEXEC') or die('Restricted access');


if (file_exists(JPATH_BASE.'/components/com_eventgallery/config_override.php')) {
	require_once JPATH_BASE.'/components/com_eventgallery/config_override.php';
}

// defines the path to the image source folder
if (!defined ('COM_EVENTGALLERY_IMAGE_FOLDER_PATH')) {
	define('COM_EVENTGALLERY_IMAGE_FOLDER_PATH', JPATH_BASE . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR . 'eventgallery' . DIRECTORY_SEPARATOR);
}

// defines the path to the image source folder
if (!defined ('COM_EVENTGALLERY_IMAGE_FOLDER_PATH_WEB')) {
	define('COM_EVENTGALLERY_IMAGE_FOLDER_PATH_WEB', 'images/eventgallery/');
}

// defines the path to the image cache folder
if (!defined('COM_EVENTGALLERY_IMAGE_CACHE_PATH')) {
	define('COM_EVENTGALLERY_IMAGE_CACHE_PATH', JPATH_CACHE . DIRECTORY_SEPARATOR . 'com_eventgallery_images' . DIRECTORY_SEPARATOR);
}

// defines the path to path to the image cache folder for an url 
if (!defined('COM_EVENTGALLERY_IMAGE_CACHE_PATH_WEB')) {
	define('COM_EVENTGALLERY_IMAGE_CACHE_PATH_WEB', 'cache/com_eventgallery_images/');
}

// defines the path to the picasa xml cache folder
if (!defined('COM_EVENTGALLERY_PICASA_CACHE_PATH')) {
	define('COM_EVENTGALLERY_PICASA_CACHE_PATH', preg_replace('/administrator[\/\\\\]+/', '', JPATH_CACHE . DIRECTORY_SEPARATOR . 'com_eventgallery_picasa' . DIRECTORY_SEPARATOR));
}

// maximum available image size
define('COM_EVENTGALLERY_IMAGE_ORIGINAL_MAX_WIDTH', 1440);